name: Main
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  quality:
    name: Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set SHAs
        uses: nrwl/nx-set-shas@v3

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npx nx format:check

      - name: Lint code
        run: npx nx affected -t lint --parallel=3

      - name: Run tests
        run: npx nx affected -t test --parallel=3 --configuration=ci
